- name: 'iTerm2: Add configuration'
  tags:
    - config
    - iterm2
  template:
    src: "{{ item }}"
    dest: '~/.iterm2'
    mode: '0600'
  loop: "{{ query('fileglob', 'iterm2/*') }}"

- name: 'Firefox: Set base path'
  tags:
    - config
  set_fact:
    firefox_path: '~/Library/Application Support/Firefox'

- name: 'Firefox: Find profile path'
  tags:
    - config
  set_fact:
    profile_path: "{{ lookup('ini', 'Path section=Profile0 file=' + firefox_path + '/profiles.ini') }}"

- name: 'Firefox: Add local config'
  tags:
    - config
  copy:
    content: |
      user_pref("geo.enabled", false);
      user_pref("privacy.window.maxInnerWidth", 1400);
      user_pref("privacy.window.maxInnerHeight", 900);
    dest: "{{ firefox_path  }}/{{ profile_path }}/user.js"
    mode: '0600'

- name: 'OS X: Dock orientation'
  tags:
    - config
  osx_defaults:
    domain: com.apple.dock
    type: string
    key: orientation
    value: right

- name: 'OS X: Dock size'
  tags:
    - config
  osx_defaults:
    domain: com.apple.dock
    type: float
    key: tilesize
    value: '35'

- name: 'OS X: Smart quotes off'
  tags:
    - config
  osx_defaults:
      domain: NSGlobalDomain
      type: int
      key: NSAutomaticQuoteSubstitutionEnabled
      value: '0'

- name: 'OS X: Smart dashes off'
  tags:
    - config
  osx_defaults:
      domain: NSGlobalDomain
      type: int
      key: NSAutomaticDashSubstitutionEnabled
      value: '0'

- name: 'OS X: Spell correction off'
  tags:
    - config
  osx_defaults:
      domain: NSGlobalDomain
      type: int
      key: NSAutomaticSpellingCorrectionEnabled
      value: '0'

- name: 'OS X: Web spell correction off'
  tags:
    - config
  osx_defaults:
      domain: NSGlobalDomain
      type: int
      key: WebAutomaticSpellingCorrectionEnabled
      value: '0'

- name: 'OS X: Clear preferences cache'
  tags:
    - config
  command: 'pkill -u ${USER} cfprefsd'
