- name: "Searx"
  tags:
    - searx
  block:
    - include: roles/common_server/tasks/docker.yaml

    - name: "Searx: Config directory"
      tags:
        - install
      file:
        state: directory
        path: "{{ item }}"
      loop:
        - "/srv/app/docker/searx"
        - "/srv/app/docker/searx/config"
        - "/srv/app/docker/searx/config/plugins"
        - "/srv/app/docker/searx/config/engines"
      become: yes

    - name: "Searx: Config: main"
      tags:
        - config
      template:
        dest: "/srv/app/docker/searx/config/settings.yml"
        src: "templates/settings.yaml.j2"
        mode: "0400"
      become: yes

    - name: "Searx: Config: overrides"
      tags:
        - config
      copy:
        dest: "/srv/app/docker/searx/config/{{ item }}/"
        src: "files/{{ item }}/"
      loop:
        - "plugins"
        - "engines"
      become: yes

    - name: "Searx: Docker: compose.yaml"
      tags:
        - config
      copy:
        dest: "/srv/app/docker/searx/compose.yaml"
        src: "files/docker-compose.yaml"
        mode: "0400"
      become: yes
