- name: Checkout some repositories for local config
  tags:
    - config
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
  loop: "{{ config_repos }}"

- name: 'Conky: Configuration'
  tags:
    - config
    - conky
  template:
    src: 'templates/conkyrc.j2'
    dest: '~/.conkyrc'
    mode: '0600'

- name: 'Wireguard: Configuration template'
  tags:
    - config
    - wireguard
  block:
    - stat:
        path: /etc/wireguard/wg0.conf
      register: wgconfig
    - copy:
        dest: /etc/wireguard/wg0.conf
        src: files/wireguard.conf
        mode: '0400'
      when: wgconfig.stat.exists == False
      become: true
