- name: 'Config: Checkout some repositories for local config'
  tags:
    - config
    - repos
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
  loop: "{{ config_repos }}"

- name: 'Conky: Configuration'
  tags:
    - config
    - conky
  template:
    src: 'templates/conkyrc.j2'
    dest: '~/.conkyrc'
    mode: '0400'

- name: 'Wireguard'
  tags:
    - config
    - wireguard
  block:
    - set_fact:
        wgconfig_path: /etc/wireguard/wg0.conf

    - name: 'Wireguard: Check for existing configuration'
      stat:
        path: "{{ wgconfig_path }}"
      register: wgconfig

    - name: 'Wireguard: Create configuration template'
      copy:
        dest: "{{ wgconfig_path }}"
        src: files/wireguard.conf
        mode: '0400'
      when: wgconfig.stat.exists == False
      become: true

    - name: 'Wireguard: Fix configuration permissions'
      file:
        state: file
        path: "{{ wgconfig_path }}"
        mode: '0400'
        owner: 'root'
        group: 'root'
      become: true

    - name: 'Wireguard: Service enabled'
      service:
        name: 'wg-quick@wg0'
        enabled: true
        state: started

- name: 'Abert'
  tags:
    - config
    - albert
  copy:
    dest: '~/.config'
    src: files/albert
