- name: Checkout some repositories for local config
  tags:
    - config
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
  loop: "{{ config_repos }}"

- name: Conky configuration
  tags:
    - config
    - conky
  template:
    src: templates/conkyrc.j2
    dest: ~/.conkyrc
    mode: "0600"
