- name: Adding repositories
  tags:
    - install
  apt_repository:
    repo: "{{ item }}"
    state: present
  loop: "{{ linux_repos }}"
  become: true

- name: Installing packages
  tags:
    - install
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ linux_packages }}"
  become: true

- name: Installing Snaps
  tags:
    - install
#   snap:
#     name: "{{ item }}"
#     state: present
  command: "snap install {{ item }}"
  loop: "{{ linux_apps }}"
  become: true

- name: Checking for Modern Pictogram font
  tags:
    - install
  stat:
    path: '~/.local/share/fonts/modernpics.otf'
  register: fontfile

- name: Installing fonts
  tags:
    - install
  block:
    - name: Create temporary file for Modern Pictograms font
      tempfile:
        state: file
        suffix: '.zip'
      register: fontzip

    - name: Download Modern Pictograms font
      get_url:
        url: https://www.fontsquirrel.com/fonts/download/modern-pictograms
        dest: "{{ fontzip.path }}"
        force: true
      register: fetchurl

    - name: Unzip Modern Pictograms font
      unarchive:
        src: "{{ fontzip.path }}"
        dest: '~/.local/share/fonts'
        exclude: '*.txt'

    - name: Remove temporary file
      file:
        path: "{{ fontzip.path }}"
        state: absent

    - name: Refresh font cache
      command: 'fc-cache -f'
  when: fontfile.stat.exists == false
