- name: Desktop installation and configuration
  hosts: desktop
  roles:
    - role: linux_desktop
      when: ansible_system == 'Linux'
      tags:
        - linux
    - role: darwin_desktop
      when: ansible_system == 'Darwin'
      tags:
        - darwin
        - osx
