- name: Desktop installation and configuration
  hosts: desktop
  roles:
    - role: desktop
  vars_files:
    - "roles/desktop/vars/{{ ansible_system|lower }}.yaml"
    - "roles/desktop/vars/common.yaml"
