- name: "Matrix: Configuration"
  tags:
    - config
    - matrix
  block:
    - include: roles/common_server/tasks/docker.yaml

    - name: "Matrix: Configuration: homeserver.yaml"
      template:
        src: "templates/homeserver.yaml.j2"
        dest: "/srv/app/docker/matrix/config/homeserver.yaml"
        mode: "0400"
        owner: "matrix-synapse"
        group: "nogroup"
      become: yes

    - name: "Matrix: Configuration: homeserver.signing.key"
      copy:
        dest: "/srv/app/docker/matrix/config/homeserver.signing.key"
        content: "{{ signing_key }}"
        mode: "0400"
        owner: "matrix-synapse"
        group: "nogroup"
      become: yes

    - name: "Matrix: Docker: compose.yaml"
      copy:
        dest: "/srv/app/docker/matrix/compose.yaml"
        src: "files/docker-compose.yaml"
        mode: "0400"
      become: yes
