- name: 'Matrix: Repositories'
  tags:
    - install
    - repos
    - matrix
  include: includes/repos.yaml
  loop: "{{ linux_repos }}"
  loop_control:
    loop_var: repo

- name: 'Matrix: Packages'
  tags:
    - install
    - packages
    - matrix
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ linux_packages }}"
  become: true

- name: 'Matrix: Configuration'
  tags:
    - config
    - matrix
  template:
    src: 'templates/homeserver.yaml.j2'
    dest: '/etc/matrix-synapse/homeserver.yaml'
    mode: '0400'
    owner: 'matrix-synapse'
    group: 'nogroup'
  become: yes
