- name: Adding repositories
  tags:
    - install
    - repos
    - matrix
  include: includes/repos.yaml
  loop: "{{ linux_repos }}"
  loop_control:
    loop_var: repo

- name: Installing packages
  tags:
    - install
    - packages
    - matrix
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ linux_packages }}"
  become: true
