- name: 'Basics: Package installs'
  tags:
    - install
    - basics
  yum:
    name: "{{ item }}"
    state: latest
  loop: "{{ server_packages }}"
  become: yes

- name: 'Basics: Directories'
  tags:
    - basics
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /srv
    - /srv/app
    - /srv/tmp
    - /srv/etc
  become: yes

- name: 'Basics: Temp dir perms'
  tags:
    - basics
  file:
    path: '/srv/tmp'
    mode: '1777'
  become: yes
