- name: includes/repos.yaml
  tags:
    - install
    - repos
    - matrix
  block:
    - name: "Apt repo: Import GPG key: {{ repo.name }}"
      apt_key:
        state: present
        url: "{{ repo.key }}"
      when: repo.key
      become: true

    - name: "Apt repo: Add repo: {{ repo.name }}"
      apt_repository:
        state: present
        repo: "{{ repo.data }}"
        update_cache: yes
      become: true
