- name: Basic package installs
  tags:
    - install
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - epel-release
    - git
    - lsof
    - net-tools
    - psmisc
    - rsync
    - telnet
    - vim
  become: true