- name: "Media Server"
  tags:
    - mediaserver
  block:
    - include: roles/common_server/tasks/docker.yaml

    - name: "Media Server: Group"
      tags:
        - install
      group:
        name: "media"
      become: yes

    - name: "Media Server: User"
      tags:
        - install
      user:
        name: "media"
        group: "media"
        comment: "Media Server user"
        expires: -1
      become: yes

    - name: "Media Server: directories"
      tags:
        - config
      file:
        path: "{{ item }}"
        state: directory
        owner: "media"
        group: "media"
      loop:
        - "/srv/app/docker/mediaserver"
        - "/srv/app/docker/mediaserver/config"
      become: yes

    - name: "Media Server: Docker: compose.yaml"
      tags:
        - config
      copy:
        dest: "/srv/app/docker/mediaserver/compose.yaml"
        src: "files/docker-compose.yaml"
        mode: "0400"
      become: yes
