- name: "Media Server"
  tags:
    - mediaserver
  block:
    - name: "Media Server: Group"
      tags:
        - install
        - docker
      group:
        name: "media"
      become: yes

    - name: "Media Server: User"
      tags:
        - install
        - docker
      user:
        name: "media"
        group: "media"
        comment: "Media Server user"
        expires: -1
      become: yes

    - name: "Media Server: Docker: packages"
      tags:
        - install
        - docker
      package:
        name: "{{ item }}"
        state: latest
      loop:
        - "docker.io"
        - "docker-compose"
      become: yes

    - name: "Media Server: Docker: directories"
      tags:
        - config
        - docker
      file:
        path: "/srv/app/docker/mediaserver/config"
        state: directory
        owner: "media"
        group: "media"
        recurse: yes
      become: yes

    - name: "Media Server: Docker: config"
      tags:
        - config
        - docker
      copy:
        dest: "/srv/app/docker/mediaserver/compose.yaml"
        src: "files/docker-compose.yaml"
      become: yes
