- name: 'Platform: Google Laptop (Chromebook)'
  tags:
    - platform

  block:
    - name: 'Platform: Google Laptop: Audio drivers'
      unarchive:
        src: files/google-laptop-audio.tar.gz
        dest: /
      become: true

    - name: 'Platform: Google Laptop: Disable wireless power management'
      lineinfile:
        path: /etc/NetworkManager/conf.d/default-wifi-powersave-on.conf
        regexp: '^wifi.powersave ='
        line: 'wifi.powersave = 2'
      become: true

    - name: 'Platform: Google Laptop: Make WiFi stable'
      lineinfile:
        path: /etc/modprobe.d/iwlwifi.conf
        regexp: '^options iwlwifi '
        line: 'options iwlwifi 11n_disable=8 swcrypto=1'
      become: true

    - name: 'Synaptics touchpad natural scrolling'
      copy:
        dest: '/etc/X11/Xsession.d/80synaptics'
        content: |
          synclient VertScrollDelta=-247
          synclient HorizScrollDelta=-247
        mode: '0644'
        owner: 'root'
        group: 'root'
      become: true

    - name: 'Enable touchscreen in Firefox'
      tags:
        - firefox
        - config
      copy:
        dest: '/etc/environment.d/99firefox.conf'
        content: 'MOZ_USE_XINPUT2=1'
        mode: '0444'
        owner: 'root'
        group: 'root'
      become: yes
