- name: 'Platform: Google Laptop (Chromebook)'
  tags:
    - platform

  block:
    - name: 'Platform: Google Laptop: Audio drivers'
      unarchive:
        src: files/google-laptop-audio.tar.gz
        dest: /
      become: true

    - name: 'Platform: Google Laptop: Disable wireless power management'
      copy:
        dest: /etc/pm/sleep.d/wifi_pwr_off
        content: '/sbin/iwconfig wlp1s0 power off'
        mode: '0500'
      become: true
