config_repos:
  - name: 'albert'
    repo: 'git@github.com:scottwallacesh/albert.git'
    dest: '~/.local/share/albert'

linux_repos:
  - 'deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main'             # Visual Studio Code
  - 'deb http://download.opensuse.org/repositories/home:/manuelschneid3r/xUbuntu_18.10/ /' # Albert
  - 'deb http://linux-packages.resilio.com/resilio-sync/deb resilio-sync non-free'         # Resilio Sync
  - 'deb http://prerelease.keybase.io/deb stable main'                                     # Keybase
  - 'deb https://apt.enpass.io/ stable main'                                               # Enpass

linux_repos_keys:
  - 'https://packages.microsoft.com/keys/microsoft.asc'                                         # Visual Studio Code
  - 'https://download.opensuse.org/repositories/home:manuelschneid3r/xUbuntu_18.10/Release.key' # Albert
  - 'http://linux-packages.resilio.com/resilio-sync/key.asc'                                    # Resilio Sync
  - 'https://keybase.io/docs/server_security/code_signing_key.asc'                              # Keybase
  - 'https://apt.enpass.io/keys/enpass-linux.key'                                               # Enpass

linux_packages:
  - albert
  - chrome-gnome-shell
  - code
  - conky
  - copyq
  - dconf-editor
  - enpass
  - git
  - glances
  - gnome-shell-extension-caffeine
  - gnome-shell-extension-dashtodock
  - gnome-shell-extension-mediaplayer
  - gnome-shell-extension-weather
  - gnome-tweaks
  - keybase
  - net-tools
  - netcat
  - qrencode
  - resilio-sync
  - screen
  # - sonos-controller-unofficial
  - ttf-mscorefonts-installer
  - units
  - vim
  - wireshark-qt

linux_apps:
  #  - franz
  - google-play-music-desktop-player
  - 'skype --classic'
  - wireguard-ammp

gnome_extension_ids:
  - 358    # activities configurator
  - 1206   # clock-override
  - 28     # gtile
  - 1386   # notification counter
  - 19     # user themes

# Platform specific packages
# Format: systemvendor_formfactor_packages
"Apple Inc._Laptop_packages":
  - mbpfan
